code --install-extension kaiwood.center-editor-window
code --install-extension formulahendry.code-runner
code --install-extension mikestead.dotenv
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension dbaeumer.vscode-eslint
code --install-extension oliversturm.fix-json
code --install-extension waderyan.gitblame
code --install-extension bierner.github-markdown-preview
code --install-extension alekseychaikovsky.line-jumper
code --install-extension bierner.markdown-checkbox
code --install-extension bierner.markdown-emoji
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bierner.markdown-yaml-preamble
code --install-extension Equinusocio.vsc-material-theme
code --install-extension pnp.polacode
code --install-extension esbenp.prettier-vscode
code --install-extension ow.vscode-subword-navigation
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension dansilver.typewriter
code --install-extension AleksandarDev.vscode-sequence-diagrams
code --install-extension robertohuertasm.vscode-icons
